triggers = {
    "I need help": 0,
    "Will someone help me": 0,
    "Can someone please help me": 0,
    "I have a question": 0,
    "Will someone answer my question": 0,
    "What is the prefix for starboard": 1,
    "What is the prefix for the bot": 1,
    "What is the prefix": 1,
    "Starboard isn't working": 2,
    "The bot isn't working": 2,
    "The bot isn't responding": 2,
    "Starboard isn't responding": 2,
    "Starboard won't work": 2,
    "The bot won't work": 2,
    "Starboard won't respond": 2,
    "The bot won't respond": 2,
    "What can Starboard do": 3,
    "What can this bot do": 3,
    "How does the bot work": 3,
    "How does starboard work": 3,
    "How does it work": 3,
    "What does Starboard do": 3,
    "What does this bot do": 3,
    "What is a starboard": 3,
    "How do I use starboard": 4,
    "How do I use this bot": 4,
    "How do I setup starboard": 4,
    "How do I setup the bot": 4,
    "How do I set the bot up": 4,
    "How do I set starboard up": 4,
    "How do I invite starboard": 5,
    "How do I invite the bot": 5,
    "How do I add starboard": 5,
    "How do I add the bot": 5,
    "Starboard invite link": 5,
    "Is starboard offline": 6,
    "Is the bot offline": 6,
    "Can I change the prefix": 7,
    "How do I change the prefixes": 7,
    "How do I change the prefix": 7,
    "Is the prefix customizable": 7,
    "Can I have custom prefixes": 7,
    "Are the prefixes customizable": 7,
    "How do I customize the prefix": 7,
    "How do I customize the prefixes": 7
}

responses = {
    0: "What do you need help with?",
    1: "The default prefix for Starboard is `sb!` or its mention.",
    2: "Please elaborate on your issue and what you have tried.\nYou can also look here for troubleshooting <https://github.com/CircuitsBots/Starboard/wiki/Troubleshooting>",
    3: "A starboard is a bot that allows users to star messages by reacting to them with :star:. When a message receives a certain number of stars, it is reposted in a channel usually called #starboard.",
    4: "Please look at the quick start guide here: <https://github.com/CircuitsBots/Starboard/wiki/Quick-Setup>",
    5: "You can invite Starboard to your server with this link: <https://discord.com/api/oauth2/authorize?client_id=700796664276844612&permissions=388160&scope=bot>",
    6: "If the bot is offline, it will probably be back soon. Please be patient.",
    7: "You can see one of starboards prefixes by mentioning it. From there, you can run `[p]prefix add <prefix>` or `[p]prefix remove <prefix>` to customize them."
}